customer/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name ='customer'

urlpatterns = [
    path("",views.customer_profile,name="customer"),
    path("customer-update/<str:pk>/",views.customer_update,name="customer_update"),
    path("customer-delete/<str:pk>/",views.customer_delete,name="customer_delete"),
    path("create-order/<str:pk>/",views.create_or_get_order,name='createorder'),
    path('momprofile/<str:pk>/',views.MomProfileView,name="momprofile"),
    path('momprofile/',views.MomsProfileView,name="mom-profile"),
    path('order-view/',views.OrderView,name="orderview"),
    path('buy/<str:pk>/',views.buy_order,name='buy'),
    path('delete-item/<str:pk>/',views.order_item_delete,name="deleteitem"),
    path('delete-order/<str:pk>/',views.order_delete,name="delete_order"),
    path('notify-customer/',views.notify_purchase_to_customer,name='notify_customer'),
    path('payment/<str:pk>/',views.accept_order_payment,name='accept-order-payment'),
    path('recipt/',views.recipt,name='recipt'),
]

kitchen/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mom.urls')),
    path('customer/',include('customer.urls')),
    path('register/',include('validations.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

mom/urls.py
from django.urls import path
from . import views
from validations.views import LoginPage,Logout
app_name = 'moms'

urlpatterns = [
    path("",views.HomeView,name="home"),
    
    path("product/<str:pk>/",views.ProductView,name='product'),
    path("product-view/",views.ProductViewPage,name='productview'),

    path('profile/',views.ProfileView,name="profile"),
    path('update-profile/<str:pk>/',views.ProfileUpdateView,name='updateprofile'),
    path('delete-profile/',views.ProfileDelete,name="deleteprofile"),
    
    path("menu/",views.CreateMenu,name="menu"),
    path("menu-update/<str:pk>/",views.MenuUpdateView,name="menuupdate"),
    path("menu-delete/<str:pk>/",views.MenuDeleteView,name="menudelete"),

    path('menuitem/',views.createMenuItem,name='menuitems'),
    path('menuview/<str:mom_id>/item/<str:menu_id>/',views.MenuItemView,name='menuview'),
    path('itemupdate/<str:pk>/',views.MenuItemUpdateView,name='itemupdate'),
    path('itemdelete/<str:pk>/',views.MenuItemDeleteView,name='itemdelete'),
    
    path('notify-mom/',views.notify_purchase_to_mom,name='notify_mom'),
    path('order-accept/<str:pk>/',views.order_accept,name="order_accept"),
    
    path('mom-view/',views.mom_view,name="mom_view"),
    
    path("login/",LoginPage,name="login"),
    path("logout/",Logout,name="logout"),
    
]

 

customer/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    email = models.EmailField()
    phone_number = models.CharField(max_length=10)
    address = models.CharField(max_length=200)
    profile = models.ImageField(upload_to="customer/profile/")

    def __str__(self):
        return self.user.username

customer/forms.py
from django import forms
from customer.models import Customer
class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['phone_number','address','profile']
        exclude = ['user','email']

mom/forms.py
from .models import *
from django import forms



class MomForm (forms.ModelForm):
    class Meta:
        model = MomModel
        fields = '__all__'
        exclude = ['user','email']


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['name','description']
        exclude = ['moms']

class MenuItemForm(forms.ModelForm):
    menu = forms.ModelChoiceField(queryset=Menu.objects.all())

    class Meta:
        model = MenuItem
        fields = ['menu','name','price','item_image','description','is_available']
    # show related option that only the autheticated user can modify their own data in relationship cannot view other related data 
    def __init__(self,*args,**kwargs):
        user = kwargs.pop('user',None)
        super().__init__(*args,**kwargs)
        if user:
            self.fields['menu'].queryset = Menu.objects.filter(moms__user = user)

customer/views.py
from django.shortcuts import render,HttpResponse,redirect
from mom.models import *
from django.contrib.auth.models import User,AnonymousUser
from django.conf import settings
from django.conf.urls.static import static
from customer.forms import CustomerForm

# Create your views here.

def customer_profile (request):
    if request.user.is_authenticated == True:
        user = User.objects.get(id = request.user.id)
        for groupfetch in user.groups.all():
            if (str(groupfetch) == "moms" or str(groupfetch) == "customer" or str(groupfetch) == "delivery"):
                groupname = groupfetch            
        if str(groupname) == "moms":
            return redirect('moms:profile')
        elif str(groupname) == "customer":
            if request.user.is_authenticated == True:
                email = request.user.email
                cust_obj = Customer.objects.get(email=email)
                order = cust_obj.customer.all()
                order_count = order.count()
                context = {'cust_obj': cust_obj,'order_count':order_count,'orders':order}
                return render(request,'customer/customer_profile.html',context)
    
    return redirect("moms:login")

    # if isinstance(request.user,AnonymousUser):
    #     return redirect('moms:home')

def customer_update(request,pk):
    cust_obj = Customer.objects.get(id=pk)
    form = CustomerForm(instance=cust_obj)
    if request.method == 'POST':
        form = CustomerForm(request.POST,request.FILES,instance=cust_obj)
        if form.is_valid():
            form.save()
            return redirect('customer:customer')
    context = {"form":form,"formname":"update"}
    return render(request,'customer/forms.html',context)

def customer_delete(request,pk):
    cust_obj = Customer.objects.get(id=pk)
    if request.method == 'POST':
        cust_obj.delete()
        return redirect('moms:logout')
    return render(request,'customer/delete.html')


def MomProfileView(request,pk):
    moms = MomModel.objects.get(id=pk) 
    menus = moms.momsmenu.all()
    menu_item = MenuItem.objects.filter(menu__in = menus)  
    print(menu_item)
    context = {'moms':moms,'menus':menus,'menu_item':menu_item}
    return render(request,'customer/mom_profile.html',context)

def MomsProfileView(request):
    moms = MomModel.objects.all()
    context = {"moms":moms}
    return render(request,'customer/mom.html',context) 

def create_or_get_order(request,pk):
    user = User.objects.get(id=request.user.id)
    print("user : ",user)
    group_name = user.groups.all()[0]
    print("outside groupname",group_name)
    if str(group_name) == "customer":
        try:
            customer = Customer.objects.get(user=user)
            item = MenuItem.objects.get(id=pk)
            print("item: ",item)
            order,created = Order.objects.get_or_create(customer=customer,moms=item.menu.moms )
            # order,created = Order.objects.create(customer=customer,moms=item.menu.moms )
            order.items.add(item)
            orderitem,created = OrderItem.objects.get_or_create(order=order,menu_item=item)
            orderitem.status = 'pending'
            orderitem.quantity += 1
            orderitem.save()
            # print("orderitem",orderitem)
            # print("orderitem quantity",orderitem.quantity)
            return redirect ('customer:orderview')
        except Exception as e:
            print("exception ",e)
    
    return HttpResponse("couldnot created")


def OrderView(request):
    item_with_id = request.GET.get('item_id')
    operation = request.GET.get('operation')
    user = User.objects.get(id=request.user.id)
    customers = Customer.objects.get(user=user)
    orders = customers.customer.all()
    context = {'orders':orders}
    if request.method == "GET":
        if item_with_id and operation:
            try:
                item = OrderItem.objects.get(id=item_with_id)
                item.updated_quantity(operation)
            except Exception as e:
                print("error",e)

    # print("item with id " ,item_with_id)
    # print("operation " ,operation)
    # item = OrderItem.objects.get()
    return render(request,'customer/order.html',context)

def order_item_delete(request,pk):
    item = OrderItem.objects.get(id=pk) 
    if request.method == 'POST':
        item.delete()
        return redirect('customer:orderview')
    context = {"item":item}
    return render(request,'customer/delete.html',context)
    
def order_delete(request,pk):
    item = Order.objects.get(id=pk) 
    if request.method == 'POST':
        item.delete()
        return redirect('customer:orderview')
    context = {"item":item}
    return render(request,'customer/delete.html',context)

def buy_order(request,pk):
    ordered_item_obj = OrderItem.objects.get(id=pk) #id=13
    order_placed_obj,created = OrderPlaced.objects.get_or_create(order_placed=ordered_item_obj,is_placed = True)
    print("order id created",created)
    print("buy order")
    context = {'ordered_item':ordered_item_obj,'order_placed':order_placed_obj}
    return render(request,'customer/buy_now.html',context)
    
def notify_purchase_to_customer(request):
    if request.user.is_authenticated == True:
        user = User.objects.get(id=request.user.id) 
        for groupfetch in user.groups.all():
            if (str(groupfetch) == "customer"): 
                customer = Customer.objects.get(email=user.email)
                order_query = customer.notify_order_accept_customer.all() 
                for notify in order_query:
                    print("notify id: ",notify.id)

                context = {"order_message":order_query}
                return render(request,"customer/notification.html",context)
            
            return redirect('moms:login')
    
    return redirect('moms:login')

def accept_order_payment(request,pk):
    order_accept_notification = OrderAcceptNotifcation.objects.get(id=pk)
    order_accept_id = order_accept_notification.order_accept.id
    order_accept_obj = OrderAccept.objects.get(id=order_accept_id)
    total_price = order_accept_obj.order_placed.order_placed.total_price
    quantity = order_accept_obj.order_placed.order_placed.quantity
    
    item_name = order_accept_obj.order_placed.order_placed.menu_item.name
    payment = Payment.objects.get_or_create(payment_method="e-pay", total_amount=total_price,order_accept=order_accept_obj)
    if request.method == "POST":
        recipt = Recipt.objects.get_or_create(payment=payment,recipt_name=item_name)
        return redirect('customer:recipt')
    context = {'payment':payment,'quantity':quantity,'item_name':item_name,'total_price':total_price}
    return render(request, 'customer/payment.html',context)


def recipt(request):

    context = {}
    return render(request,'customer/recipt.html',context)

customer/templates/customer/base.html
{% load static %} {% comment %} {% load static %} {% endcomment %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>customer</title>
    <link rel="stylesheet" href="{% static 'customer/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'customer/css/all.min.css' %}" />
    {% block style %} {% endblock style %}
  </head>
  <body>

      {% include "customer/navbar.html" %} 
      {% block content %} {% endblock content %}
    <script src="{% static 'customer/js/jquery.js' %}"></script>
    <script src="{% static 'customer/js/all.min.js' %}"></script>
  </body>
</html>

customer/templates/customer/buy_now.html
{% extends "customer/base.html" %}
{% block style %}
<style>
    /* Container Styles */
    .container {
        max-width: 900px;
        margin: 20px auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        background-color: #ffffff;
    }

    /* Order Styles */
    .order {
        background-color: #28a745;
        color: #fff;
        text-align: center;
        padding: 10px;
        font-size: 20px;
        border-radius: 5px;
    }

    .order_placed {
        margin-top: 20px;
        text-align: center;
    }

    .order_placed p {
        font-size: 18px;
        margin: 10px 0;
    }

    .order_placed a {
        display: inline-block;
        text-decoration: none;
        background-color: #007bff;
        color: #fff;
        padding: 5px 10px;
        border-radius: 5px;
        font-size: 16px;
        margin-top: 10px;
    }

    .order_placed a:hover {
        background-color: #0056b3;
    }

    /* Item Styles */
    .item {
        display: flex;
        margin-top: 20px;
    }

    .image img {
        width: 250px;
        height: 200px;
        border-radius: 5px;
    }

    .detailtext {
        margin-left: 20px;
    }

    .inline {
        margin: 5px 0;
    }
</style>

{% endblock style %}
{% block content %}
<div class="order">Order Placed Successfully</div>

<div class="container">
    <div class="ordered_item">
        <div class="item">
            <div class="image">
                {% if ordered_item.menu_item.item_image.url != None %}
                <img width="250px" height="200px" src="{{ ordered_item.menu_item.item_image.url }}" alt="item image" srcset="">
                {% else %}
                <img width="450px" height="350px" src="" alt="item image" srcset="">
                {% endif %}
            </div>
            <div class="detailtext">
                <div class="inline">Item Name: {{ ordered_item.menu_item.name }}</div>
                <div class="inline">Price: {{ ordered_item.menu_item.price }}</div>
                <div class="inline">Total Price: {{ order_placed.order_placed.total_price }}</div>
                <div class="inline">No of Quantity: {{ order_placed.order_placed.quantity }}</div>
                <div class="inline">Description: {{ ordered_item.menu_item.description }}</div>
                <div class="inline">Available: {{ ordered_item.menu_item.is_available }}</div>
                <div class="inline">Created At:</div>
                <div class="inline">Expiry At:</div>
            </div>
        </div>
    </div>
    <div class="order_placed">
        <p>Order is placed. Request is sent for Order ID: {{ order_placed.id }}</p>
        <p>Order is requested for the mom "{{ order_placed.order_placed.order.moms }}"</p>
        <a href="{% url 'moms:home' %}">Home</a>
    </div>
</div>

{% endblock content %}

customer/templates/customer/cart.html
{% extends "customer/base.html" %}

{% block content %}
<h1>cart page</h1>

{% endblock content %}

customer/templates/customer/customer_profile.html
{% extends "customer/base.html" %}

{% block style %}
<style>
  /* Container Styles */
  .container {
    max-width: 900px;
    margin: 20px auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    background-color: #ffffff;
  }

  /* Alert Styles */
  .alert {
    padding: 10px;
    border-radius: 5px;
    font-size: 16px;
  }

  .alert-success {
    background-color: #dff0d8;
    border-color: #d6e9c6;
    color: #3c763d;
  }

  .alert-danger {
    background-color: #f2dede;
    border-color: #ebccd1;
    color: #a94442;
  }

  /* Profile Styles */
  .profile {
    margin-bottom: 20px;
  }

  .profile h2 {
    font-size: 24px;
    margin-bottom: 10px;
  }

  .profile p {
    font-size: 16px;
    margin: 5px 0;
  }

  .profile img {
    width: 100px;
    height: 150px;
    border-radius: 5px;
    margin-top: 10px;
  }

  .profile a {
    display: inline-block;
    margin-right: 10px;
    text-decoration: none;
    background-color: #007bff;
    color: #fff;
    padding: 5px 10px;
    border-radius: 5px;
  }

  .profile a:hover {
    background-color: #0056b3;
  }

  /* Order Styles */
  .order p {
    font-size: 16px;
    margin: 5px 0;
  }

  .order img {
    width: 250px;
    height: 200px;
  }

  .order a {
    display: inline-block;
    margin-right: 10px;
    text-decoration: none;
    background-color: #007bff;
    color: #fff;
    padding: 5px 10px;
    border-radius: 5px;
  }

  .order a:hover {
    background-color: #0056b3;
  }

</style>

{% endblock style %}

{% block content %}
<div class="container">
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tag }} m-2" id="msg" role="alert">
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}

  <div class="profile">
    <h2>Profile Page {{ cust_obj.user }}</h2>
    <div>
      <p>User: {{ cust_obj.user }}</p>
      <p>Email: {{ cust_obj.email }}</p>
      <p>Address: {{ cust_obj.address }}</p>
      <p>Phone: {{ cust_obj.phone_number }}</p>
      <p>No of Orders: {{ order_count }}</p>

      {% if cust_obj.profile.url != None %}
      <img src="{{ cust_obj.profile.url }}" alt="profile" srcset="" width="100px" height="150px" />
      {% endif %}
      <a href="{% url 'moms:logout' %}">Logout</a>
      <a href="{% url 'customer:customer_update' cust_obj.id %}">Update Profile</a>
      <a href="{% url 'customer:customer_delete' cust_obj.id %}">Delete Profile</a>
      <a href="{% url 'customer:orderview' %}">Order View</a>
      <a href="{% url 'customer:notify_customer' %}">Notification</a>
      <a href="http://facebook.com">Facebook</a>
      <a href="http://instagram.com">Instagram</a>
    </div>
  </div>
  <div class="order">
    {% for order in orders %}
    <p>Moms: {{ order.moms }}</p>
    <p>Order Date: {{ order.order_date }}</p>
    <a href="{% url 'customer:delete_order' order.id %}">Delete Order from Order Model</a>
    <hr />
    {% for item in order.order.all %}
    {% if item.menu_item.item_image.url is not None %}
    <img width="250px" height="200px" src="{{ item.menu_item.item_image.url }}" alt="" />
    {% else %}
    <img width="250px" height="200px" src="" alt="" />
    {% endif %}
    <p>Item Name: {{ item.menu_item.name }}</p>
    <p>Item Description: {{ item.menu_item.description }}</p>
    <p>Item Price: {{ item.menu_item.price }}</p>
    <p>Status: {{ item.status }}</p>
    <p>Delivered: {{ item.is_delivered }}</p>

    <a href="{% url 'customer:buy' item.id %}">Pre Order Now</a>
    <a href="{% url 'customer:deleteitem' item.id %}">Delete Item</a>
    <hr />
    {% endfor %}
    <hr />
    <hr />
    {% endfor %}
  </div>
</div>


{% endblock content %}

customer/templates/customer/delete.html
{% extends "customer/base.html" %}

{% block content %}
<h1>Are you sure ? {{item.menu_item}}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit">delete</button>

</form>
{% endblock content %}  

customer/templates/customer/delete_customer.html
{% extends "customer/base.html" %}

{% block content %}
<h1>Are you sure ? {{request.user}}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit">delete</button>

</form>
{% endblock content %}  

customer/templates/customer/forms.html
{% extends "customer/base.html" %}

{% block content %}
    <h1>{{fomrname}} form</h1> 
    <form action="" method="POST", enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit">submit</button>
    </form>
{% endblock content %}  

customer/templates/customer/mom.html
{% extends "base.html" %} 

{% block style %}
<style>
    .container{
        display: flex;
        justify-content: space-around;
        align-items : center;
    }
</style>


{% endblock style %}

{% block content %} 



<div class="container">

    {% for mom in moms %}
    
<div class="profile">
    <h2>profile page {{name}}</h2>

  <div>
    <p>kitichen name : {{mom.user}}</p>
    <p>kitichen name : {{mom.kitchen_name}}</p>
    <p>email : {{mom.email}}</p>
    <p>address : {{mom.address}}</p>
    <p>phone : {{mom.phone_number}}</p>

    {% if mom.profile.url != None %}
    <img
    src="{{mom.profile.url}}"
      alt="profile"
      srcset=""
      width="100px"
      height="150px"
      />
      {% endif %}

    </div>
</div>
<hr>
<hr>
{% endfor %} 
</div>
{% endblock content %}

customer/templates/customer/mom_profile.html
{% extends "customer/base.html" %}
{% include 'navbar.html' %}
{% comment %} context = {'moms':moms,'menus':menus,'menu_item':menu_item} {% endcomment %}
{% block style %}
<style>
    .container {
        display: flex;
        justify-content: space-evenly;
        align-items: center;
    }
    .item_container{
        display: flex;
        /* flex-direction: column; */
        justify-content: space-around;
        align-items: center;
        flex-wrap: wrap;
    }
</style>
{% endblock style %}
{% block content %}
<h1>mom profile</h1>
<div class="container">
    <div class="moms">
        <div class="images">
            {% if moms.profile.url != None %}
            <img width="200px" height="250px" src="{{moms.profile.url}}" alt="item image" srcset="" />
            {% else %}
            <img width="300px" height="200px" src="" alt="item image" srcset="" />
            {% endif %}
        </div>

        <div class="momsdetail">kitichen name: {{moms.kitichen_name}} </div>
        <div class="momsdetail">email: {{moms.email}} </div>
        <div class="momsdetail">phone number: {{moms.phone_number}} </div>
        <div class="momsdetail">cuisine_type: {{moms.phone_number}} </div>

    </div>
    <div class="menu">
        <h1> menu </h1>
        {% for menu in menus %}
        <div class="momsdetail">moms name: {{menu.moms}} </div>
        <div class="momsdetail">menu name: {{menu.moms}} </div>
        <div class="momsdetail">menu discription: {{menu.moms}} </div>
        <hr>
        <hr>
        {% endfor %}
    </div>
</div>
<div class="menu_items">
    
    <h1> menu items available </h1>
    {% for item in menu_item %}
    <div class="item_container">
        
        <div class="images">
            {% if item.item_image.url != None %}
            <img width="200px" height="250px" src="{{item.item_image.url}}" alt="item image" srcset="" />
            {% else %}
            <img width="300px" height="200px" src="" alt="item image" srcset="" />
            {% endif %}
        </div>
        <div class="momsdetail">menu name: {{item.menu}} </div>
        <div class="momsdetail">item name: {{item.name}} </div>
        <div class="momsdetail">description name: {{item.description}} </div>
        <div class="momsdetail">item price: {{item.price}} </div>
        <div class="momsdetail">available: {{item.is_available}} </div>
        <a href="{% url 'moms:product' item.id %}"> view product </a>
    
    </div>
        {% endfor %}
</div>

{% endblock content %}

customer/templates/customer/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .nav-container{

            display: flex;
            justify-content: space-around;
        }
        .navlinks ul li a{
            text-decoration: none;
            color: lightblue;
        }
        
        .navlinks ul li a:hover{
            text-decoration: underline;
            color: rgb(122, 206, 235);
        }        
        
        .navlinks ul li{
            text-decoration: none;
            list-style: none;
            margin: 0 0.3rem;   
            padding:0.3rem;
        }
        .navlinks ul{
            display: flex;
            justify-content: space-around;
        }
        .profileimage{
            border-radius: 50%;
            /* border: 1px solid red; */
            position: relative;
            top: 1rem;
        }
        .nav-profile{
            min-width: 250px;
            /* border: 1px solid red; */
            display: flex;
            justify-content: space-evenly;
        }
    </style>
</head>
<body>
    <div class="nav-container">
        <div class="logo">
            <h3>Logo</h3>           
        </div>
        <div class="navlinks">
            <ul>
                <li><a href="{% url 'moms:home' %}">Home</a></li>
                <li><a href="#">Product</a></li>
                {% if request.user.is_authenticated != True %}
                <li><a href="{% url 'moms:login' %}">Login</a></li>
                {% else  %}
                <li><a href="{% url 'moms:logout' %}">Logout</a></li>
                {% endif %}

                <li><a href="{% url 'customer:mom-profile' %}">moms</a></li>
                <li><a href="{% url 'moms:profile' %}">profile</a></li>
            </ul>
        </div>
        <div class="nav-profile">
            <h5>{{request.user}} </h5>
            {% if request.user.user_mom_profile.profile.url != None %}
            <img class="profileimage"
              src="{{request.user.user_mom_profile.profile.url}}"
              alt="profile"
              srcset=""
              width="30px"
              height="30px"
            />
            {% endif %}
            </div>
    </div>
</body>
</html>

customer/templates/customer/notification.html
{% include 'navbar.html' %}

{% block content %}
    <p> notification page:  </p>
    {% for msg in order_message %}
        <ul>
            <li>
                <p>{{msg}}</p>
                <p>{{msg.id}}</p>
            </li>
            <a href="{% url 'customer:accept-order-payment' msg.id %}">pay</a> 

        </ul>
    {% endfor %}

{% endblock content %}

customer/templates/customer/order.html
{% extends "customer/base.html" %}
{% load static %}
{% block content %}
<h3>order page</h3>

{% for order in orders %}

</div>
<div>mom name : {{order.moms}}</div>
<div>status : {{order.status}}</div>
<div>is delivered : {{order.is_delivered}}</div>
<hr/>
{% for item in order.order.all %}
{% if item.menu_item.item_image.url != None %}
<img width="300px" height="200px" src="{{item.menu_item.item_image.url}}" alt="item image" srcset="" />
{% else %}
<img width="300px" height="200px" src="" alt="item image" srcset="" />
{% endif %}

<div>item name: {{item.menu_item}}</div>
<div>quantiy : {{item.quantity}}</div>
<!-- <button onclick="updateQuantity('{{item.quantity}}','add','{{item.id}}')" >add</button> -->
<div>real price : {{item.menu_item.price}}</div>
<div>updated price : {{item.total_price}} </div>
<div>item image : {{item.menu_item.item_image}}</div>
<a href="{% url 'customer:deleteitem' item.id %}" type="submit">delete</a>
<button onclick="updateQuantity('{{item.id}}','add')" >+</button>
<button onclick="updateQuantity('{{item.id}}','sub')" >-</button>
<a href="{% url 'customer:buy' item.id %}">pre order now</a>
<hr/>
{% endfor %} 
 
<hr>
<hr>
{% endfor %}


<script>
    function updateQuantity(item_id,operation){
        var url = "{% url 'customer:orderview' %}" + '?item_id=' + item_id + '&operation=' + operation
        window.location.href = url
    }

</script>    
{% comment %} window.location.href = window.location.pathname + `?quantity=${quantity}` {% endcomment %}

{% endblock content %}

customer/templates/customer/payment.html
{% include 'navbar.html' %}

{% block style %}
<style>
  /* Container Styles */
  .payment-container {
    max-width: 500px;
    margin: 20px auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    background-color: #ffffff;
  }

  /* Order Details Styles */
  .order-details {
    margin-bottom: 20px;
  }

  .order-details p {
    font-size: 16px;
    margin: 5px 0;
  }

  /* Payment Form Styles */
  .payment-form {
    display: flex;
    flex-direction: column;
  }

  .payment-input {
    padding: 10px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  .payment-button {
    background-color: #007bff;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
  }

  .payment-button:hover {
    background-color: #0056b3;
  }
</style>


{% endblock style %}

{% block content %}
<div class="payment-container">
  <h2>Payment Page</h2>
  <div class="order-details">
    <p>Order Item Name: {{ item_name }}</p>
    <p>Total Price to be Paid: Rs {{ total_price }}</p>
    <p>Quantity: {{ quantity }}</p>
  </div>
  <form action="" method="POST" class="payment-form">
    {% csrf_token %}
    <label for="payment">Pay Amount:</label>
    <input type="text" name="payment" id="payment" class="payment-input">
    <button type="submit" class="payment-button">Pay</button>
</form>
</div>
{% endblock content %}

customer/templates/customer/recipt.html
{% include 'navbar.html' %}

{% block content %}
    <p> recipt page:  </p>

{% endblock content %}